# -*- coding: utf-8 -*-
"""NYC Shooting Cluster Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZQY04K-fWdm8i3U4Hutfotxj3So6TQSZ
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

df=pd.read_csv('/content/NYPD_Shooting_Incident_Data__Historic_.csv')

df.head()

# Convert OCCUR_DATE in actual date format
df['OCCUR_DATE'] = pd.to_datetime(df['OCCUR_DATE'])
# Convert OCCUR_TIME to actual time format
df['OCCUR_TIME'] = pd.to_datetime(df['OCCUR_TIME'], format='%H:%M:%S', errors='coerce')

df.tail()

df.shape

df.info()

df.dtypes

df.isna().sum()

# Replace missing demographic info
cols = [
    'PERP_AGE_GROUP','PERP_SEX','PERP_RACE',
    'VIC_AGE_GROUP','VIC_SEX','VIC_RACE','LOCATION_DESC'
]

for col in cols:
    df[col] = df[col].fillna('UNKNOWN')

# Drop missing values of latitude & longitude
df = df.dropna(subset=['Latitude', 'Longitude'])
# Drop columns that are completely empty
df = df.drop(columns=['LOC_CLASSFCTN_DESC', 'LOC_OF_OCCUR_DESC'])
# Filling with most repated value
df['JURISDICTION_CODE'] = df['JURISDICTION_CODE'].fillna(
    df['JURISDICTION_CODE'].mode()[0]
)

df.isna().sum()

"""EDA

"""

df['hour'] = df['OCCUR_TIME'].dt.hour
plt.figure(figsize=(10,5))
sns.countplot(x='hour', data=df)
plt.title("Shootings by Hour of Day")
plt.show()

"""This pattern indicates that shootings are more frequent during nighttime hours"""

df['day_name'] = df['OCCUR_DATE'].dt.day_name()

plt.figure(figsize=(10,5))
sns.countplot(
    x='day_name',
    data=df,
    order=['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday']
)
plt.title("Shootings by Day of Week")
plt.show()

"""Weekends show relatively higher shooting incidents."""

df['month'] = df['OCCUR_DATE'].dt.month
plt.figure(figsize=(10,5))
sns.countplot(x='month', data=df)
plt.title("Shootings by Month")
plt.show()

"""The peak in incidents is observed around June, July, and August"""

df['Year']= df['OCCUR_DATE'].dt.year
df.groupby('Year').size().plot(marker='o')
plt.title("Year-wise Shooting Trend")
plt.xlabel("Year")
plt.ylabel("Number of Shootings")
plt.show()

"""Shooting incidents declined steadily for several years but increased sharply again in recent years."""

# Borough is  where the shooting incident occurred
plt.figure(figsize=(8,5))
sns.countplot(y='BORO', data=df)
plt.title("Shootings by Borough")
plt.show()

"""Shooting incidents are higher in Brooklyn and Bronx"""

# precincst is police are where shooting occurs
plt.figure(figsize=(10,5))
df['PRECINCT'].value_counts().head(10).plot(kind='bar')
plt.title("Top 10 Precincts by Number of Shootings")
plt.xlabel("Precinct")
plt.ylabel("Number of Shootings")
plt.show()

"""Shooting incidents mostly occur in a few police precincts, not evenly across all areas."""

# Fatal = person died,Non-fatal = person lived
sns.countplot(x='STATISTICAL_MURDER_FLAG', data=df)
plt.xticks([0,1], ['Non-Fatal','Fatal'])
plt.title("Fatal vs Non-Fatal Shootings")
plt.show()

"""Most shootings do not cause death, but deaths from shootings are still a serious problem."""

# Droping LOCATION_DESC because most of shooting place are unknown so not useful
df = df.drop(columns=['LOCATION_DESC'])

plt.figure(figsize=(8,5))
sns.countplot(y='VIC_AGE_GROUP', data=df)
plt.title("Victim Age Group Distribution")
plt.show()

"""Most shooting victims are young adults, especially those aged between 18 and 44 years."""

plt.figure(figsize=(6,4))
sns.countplot(x='VIC_SEX', data=df)
plt.title("Victim Sex Distribution")
plt.show()

"""Most shooting victims are male, while female victims represent a smaller proportion of the total cases."""

plt.figure(figsize=(6,4))
sns.countplot(x='JURISDICTION_CODE', data=df)
plt.title("Distribution of Shooting Incidents by Jurisdiction")
plt.xlabel("Jurisdiction")
plt.ylabel("Number of Incidents")
plt.xticks(
    ticks=[0,1,2],
    labels=['NYPD Patrol','NYPD Transit','NYPD Housing']
)
plt.show()

"""Most shooting incidents are handled by NYPD Patrol, while Housing and Transit jurisdictions account for fewer cases.

Feature selection
"""

cluster_df = df[
    ['hour',
     'month',
     'Latitude',
     'Longitude',
     'JURISDICTION_CODE',
     'STATISTICAL_MURDER_FLAG']
]

"""Scaling Data"""

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_scaled = scaler.fit_transform(cluster_df)

"""MODEL SELECTION
* K-MEANS CLUSTERING
* HIERARCHICAL CLUSTERING
* DBSCAN CLUSTERING





"""

from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score
import matplotlib.pyplot as plt

inertia = []
silhouette = []

K = range(2,11)
for k in K:
    kmeans = KMeans(n_clusters=k, random_state=42)
    labels = kmeans.fit_predict(X_scaled)

    inertia.append(kmeans.inertia_)
    silhouette.append(silhouette_score(X_scaled, labels))

plt.figure(figsize=(12,5))

plt.subplot(1,2,1)
plt.plot(K, inertia, marker='o')
plt.title("Elbow Method")
plt.xlabel("k")
plt.ylabel("Inertia")

plt.subplot(1,2,2)
plt.plot(K, silhouette, marker='o')
plt.title("Silhouette Score")
plt.xlabel("k")
plt.ylabel("Silhouette")

plt.show()

"""We selected k = 4 based on the elbow point and interpretability, even though silhouette scores were slightly higher at larger k values."""

cluster_df = cluster_df.copy()
kmeans = KMeans(n_clusters=4, random_state=42)
cluster_df['Cluster'] = kmeans.fit_predict(X_scaled)

cluster_df.head()

cluster_df['Cluster'].value_counts()

cluster_df.groupby('Cluster').mean()

"""* Cluster 0 represents high-severity fatal shooting incidents.
* Clusters 1 and 2 represent low-severity non-fatal shooting incidents, mainly differing by location.
* Cluster 3 represents medium-severity incidents, largely occurring in housing jurisdictions.





"""

from sklearn.cluster import AgglomerativeClustering
from sklearn.metrics import silhouette_score

agg = AgglomerativeClustering(n_clusters=4, linkage='ward')
cluster_df['AggCluster'] = agg.fit_predict(X_scaled)

# Silhouette score
agg_sil = silhouette_score(X_scaled, cluster_df['AggCluster'])
print("Agglomerative Silhouette Score:", agg_sil)

cluster_df['AggCluster'].value_counts()

cluster_df.groupby('AggCluster')[
    ['hour','month','Latitude','Longitude',
     'JURISDICTION_CODE','STATISTICAL_MURDER_FLAG']
].mean()

"""Cluster 0: Shootings that mostly happen in the evening and are
usually not fatal.

Cluster 1: Shootings that happen early in the morning and are all non-fatal.

Cluster 2: Very serious shootings where the victim died.

Cluster 3: Shootings in housing areas with both fatal and non-fatal cases.
"""

from sklearn.cluster import DBSCAN

dbscan = DBSCAN(eps=0.8, min_samples=10)
cluster_df['DBSCAN_Cluster'] = dbscan.fit_predict(X_scaled)
cluster_df['DBSCAN_Cluster'].value_counts()

plt.figure(figsize=(8,6))

# Hotspots
hotspots = cluster_df[cluster_df['DBSCAN_Cluster'] != -1]
plt.scatter(
    hotspots['Longitude'],
    hotspots['Latitude'],
    c=hotspots['DBSCAN_Cluster'],
    cmap='tab10',
    s=10,
    label='Hotspots'
)

# Noise
noise = cluster_df[cluster_df['DBSCAN_Cluster'] == -1]
plt.scatter(
    noise['Longitude'],
    noise['Latitude'],
    color='black',
    s=8,
    label='Noise'
)

plt.title("DBSCAN Hotspots and Noise")
plt.xlabel("Longitude")
plt.ylabel("Latitude")
plt.legend()
plt.show()

"""Conclusion

This project analyzed shooting incidents in New York City using machine learning clustering methods.
K-Means and Hierarchical clustering grouped incidents based on time, location, and severity.
The silhouette scores showed acceptable results for real-world crime data.
DBSCAN clearly identified high-risk shooting hotspots and separated isolated incidents.
Overall, the analysis provides useful insights that can help improve policing and public safety.
"""